### PR TITLE
Add pyproject.toml for Custom Node Registry

### PR DESCRIPTION
**Pull request by haohaocreates**
We are building a global registry for custom nodes (similar to PyPI). The registry makes using custom nodes more reliable by reserving globally unique names for each custom node, and supporting semantic versioning.

Here’s some [more information](https://www.comfydocs.org/registry/overview#introduction) on the registry.

Action Required:

- [x] Go to the [registry](https://www.comfyregistry.org/). Login and create a publisher id. Comment it here and we will update the PR (or just merge it and change it yourself).
- [x] Write a short the description.
- [ ] Merge the separate Github Actions PR and run the workflow.
If you want to publish the node manually, [install the cli](https://www.comfydocs.org/comfy-cli/getting-started#install-cli) and run `comfy node publish`

Please message me on [Discord](https://discord.com/invite/comfycontrib) if you have any questions!

### CODE REVIEW

**Comment by haohaocreates** [comment]
Saw that you merged the PR which is amazing!!!!! Was wondering if you
needed any help getting your node onto the registry?

If you merged the toml PR in first then you might have to push an update to
the file to run the GH action ahha

this is a 1m walkthrough I made if a video format helps [seems like you are
just at the last step haha] https://youtu.be/WhOZZOgBggU

**Comment by christian-byrne** [comment]
Thanks for the info. Love what you guys are doing with the registry. I got a key and added to the secrets and pushed about half an hour ago. Not seeing the update on https://www.comfyregistry.org/publishers/christian-byrne yet. I can check the workflow logs in a bit.

**Comment by christian-byrne** [comment]
Can't really tell why it didn't trigger when I pushed but I'll probably figure it out. For now I triggered it manually.

**Comment by haohaocreates** [comment]
Hey man! Appreciate the support haha

As for the GH action, HMM do you think you can push a change to your
pyproject.toml file one more time and then I can try to debug?

Thanks for trying to work this out on your end too man? 😅😇

**Comment by christian-byrne** [comment]
Just pushed again and it work now. Nice!

**Comment by haohaocreates** [comment]
Sweet! I think it was because the GH action got merged into master recently
so starting “now” it should start auto-publishing your node!

**Comment by christian-byrne** [comment]
You're definitely right. I thought it would work if I pulled first then pushed but I guess not.

BTW I just PR'ed a suggested edit to your team's comfydocs website. That website is super nice also. How did you and the rest of your team meet?

**Pull request merged**
